### ISSUE TITLE
Question about optimization

### ISSUE THREAD

**Issue by adavoli91** [google/lightweight_mmm#100]
Hi,

I'd like to ask a question about budget optimization. Before training the mmm model, I scaled both the regressors and the target, as well as the costs used to compute the prior. The prediction works well, so that I am confident about the performance of the model.

My question about the optimization process is the following: I pass the media and target scalers to the _function find_optimal_budgets_, but  should I pass the variables _prices_ and _budget_ scaled as well, or should they be in the original (i.e., unscaled) domain?

Thanks,
Alessandro

**Comment by pabloduque0** [comment]
Hello @adavoli91 !

Prices and budget should be passed "unscaled".

We use the scalers you pass to make the "connection" between the scaled data the model understands and the budget/prices which are "unscaled".

Hope it helps!

**Comment by adavoli91** [comment]
Thanks a lot
