### ISSUE TITLE
Lagging time dependence in formulas

### ISSUE THREAD

**Issue by boennecd** [google/lightweight_mmm#102]
Looking at the model in the documentation at https://lightweight-mmm.readthedocs.io/en/latest/models.html#national-level-standard-approach

The formula here shows a clear indication of time dependence: 

<img width="592" alt="Screenshot 2022-11-16 at 13 56 21" src="https://user-images.githubusercontent.com/8993362/202186495-58723381-0602-4eca-a8ba-f9a28118489c.png">

However, the "t" is missing in a lot of the subsequent formulas. Particularly, 

<img width="488" alt="Screenshot 2022-11-16 at 13 57 48" src="https://user-images.githubusercontent.com/8993362/202186808-4e8e2c82-3152-4c9e-81a5-564a1d8241c3.png">

I am guessing this should be (paste into https://latex.codecogs.com/eqneditor/editor.php)

```latex
seasonality_t = \sum_{d = 1}^2 
  \gamma_{1,d}\cos\left(\frac{2\pi dt}{52}\right) +
  \gamma_{2,d}\sin\left(\frac{2\pi dt}{52}\right)
```

Moreover, 

<img width="536" alt="Screenshot 2022-11-16 at 13 57 56" src="https://user-images.githubusercontent.com/8993362/202187592-e4365b2b-d582-4917-9903-48e553075f18.png">

I am guessing this should be 

```latex
seasonality_t = \sum_{d = 1}^2 \left(
  \gamma_{1,d}\cos\left(\frac{2\pi dt}{365}\right) +
  \gamma_{2,d}\sin\left(\frac{2\pi dt}{365}\right)\right)
  + \sum_{i=1}^7\delta_i I(t\bmod 7 =i - 1) 
```

where "I" is an indicator function. Further in 

<img width="514" alt="Screenshot 2022-11-16 at 13 58 24" src="https://user-images.githubusercontent.com/8993362/202189204-cd52ac84-cae9-4ca7-ad67-08d5f27c1b91.png">

Z seem to be missing a time index.

**Comment by michevan** [comment]
thanks a lot for flagging this! I've updated the documentation now
