### ISSUE TITLE
OOM errors with GPU 

### ISSUE THREAD

**Issue by giritatavarty-8451** [google/lightweight_mmm#103]
I have a use case which requires probably fair amount of data ( 27 channels, 644 Geos). The cpu approach takes few days, and the GPU option takes 4-5 hours but always crashes at 100% due to OOM errors.  I have tried with multiple GPUS  and memory config 16GB, 32GB, 40GB but it seems to fail everytime. 

I have also used the following XLA options but with no luck. 

os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] ='false'
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR']='platform'
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

The only thing that seems to work is to reduce the data points from 365 to 50 or something. 

`
import jax.numpy as jnp
import numpyro

from lightweight_mmm import lightweight_mmm
from lightweight_mmm import optimize_media
from lightweight_mmm import plot
from lightweight_mmm import preprocessing
from lightweight_mmm import utils

media_data, extra_features, target, costs = utils.simulate_dummy_data(
    data_size=365,
    n_media_channels=27,
    n_extra_features=1,
    geos=644) # 

mmm =  lightweight_mmm.LightweightMMM('adstock')
mmm.fit(media=media_data,
        extra_features=extra_features,
        media_prior=costs,
        target=target,
        number_warmup=1000,
        number_samples=1000,
        weekday_seasonality=False,number_chains=1)
`
**Please see the stack trace below** 

`
sample: 100%|██████████| 2000/2000 [5:02:36<00:00,  9.08s/it, 1023 steps of size 5.54e-04. acc. prob=0.93

XlaRuntimeError                           Traceback (most recent call last)
<ipython-input-4-b1a52a71abe6> in <module>
     12         number_warmup=1000,
     13         number_samples=1000,
---> 14         weekday_seasonality=False,number_chains=1)

~/.local/lib/python3.7/site-packages/lightweight_mmm/lightweight_mmm.py in fit(self, media, media_prior, target, extra_features, degrees_seasonality, seasonality_frequency, weekday_seasonality, media_names, number_warmup, number_samples, number_chains, target_accept_prob, init_strategy, custom_priors, seed)
    370         transform_function=self._model_transform_function,
    371         weekday_seasonality=weekday_seasonality,
--> 372         custom_priors=custom_priors)
    373 
    374     self.custom_priors = custom_priors

~/.local/lib/python3.7/site-packages/numpyro/infer/mcmc.py in run(self, rng_key, extra_fields, init_params, *args, **kwargs)
    592         if self.num_chains == 1:
    593             states_flat, last_state = partial_map_fn(map_args)
--> 594             states = tree_map(lambda x: x[jnp.newaxis, ...], states_flat)
    595         else:
    596             if self.chain_method == "sequential":

~/.local/lib/python3.7/site-packages/jax/_src/tree_util.py in tree_map(f, tree, is_leaf, *rest)
    205   leaves, treedef = tree_flatten(tree, is_leaf)
    206   all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 207   return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
    208 
    209 def build_tree(treedef: PyTreeDef, xs: Any) -> Any:

~/.local/lib/python3.7/site-packages/jax/_src/tree_util.py in <genexpr>(.0)
    205   leaves, treedef = tree_flatten(tree, is_leaf)
    206   all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 207   return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
    208 
    209 def build_tree(treedef: PyTreeDef, xs: Any) -> Any:

~/.local/lib/python3.7/site-packages/numpyro/infer/mcmc.py in <lambda>(x)
    592         if self.num_chains == 1:
    593             states_flat, last_state = partial_map_fn(map_args)
--> 594             states = tree_map(lambda x: x[jnp.newaxis, ...], states_flat)
    595         else:
    596             if self.chain_method == "sequential":

~/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py in _rewriting_take(arr, idx, indices_are_sorted, unique_indices, mode, fill_value)
   3815   treedef, static_idx, dynamic_idx = _split_index_for_jit(idx, arr.shape)
   3816   return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
-> 3817                  unique_indices, mode, fill_value)
   3818 
   3819 # TODO(phawkins): re-enable jit after fixing excessive recompilation for

~/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py in _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted, unique_indices, mode, fill_value)
   3852 
   3853   # This adds np.newaxis/None dimensions.
-> 3854   return expand_dims(y, indexer.newaxis_dims)
   3855 
   3856 _Indexer = collections.namedtuple("_Indexer", [

~/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py in expand_dims(a, axis)
    920   if hasattr(a, "expand_dims"):
    921     return a.expand_dims(axis)  # type: ignore
--> 922   return lax.expand_dims(a, axis)
    923 
    924 

~/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py in expand_dims(array, dimensions)
   1320     result_shape.insert(i, 1)
   1321   broadcast_dims = [i for i in range(ndim_out) if i not in dims_set]
-> 1322   return broadcast_in_dim(array, result_shape, broadcast_dims)
   1323 
   1324 

~/.local/lib/python3.7/site-packages/jax/_src/lax/lax.py in broadcast_in_dim(operand, shape, broadcast_dimensions)
    822   return broadcast_in_dim_p.bind(
    823       operand, *dyn_shape, shape=tuple(static_shape),
--> 824       broadcast_dimensions=tuple(broadcast_dimensions))
    825 
    826 def broadcast_to_rank(x: Array, rank: int) -> Array:

~/.local/lib/python3.7/site-packages/jax/core.py in bind(self, *args, **params)
    327     assert (not config.jax_enable_checks or
    328             all(isinstance(arg, Tracer) or valid_jaxtype(arg) for arg in args)), args
--> 329     return self.bind_with_trace(find_top_trace(args), args, params)
    330 
    331   def bind_with_trace(self, trace, args, params):

~/.local/lib/python3.7/site-packages/jax/core.py in bind_with_trace(self, trace, args, params)
    330 
    331   def bind_with_trace(self, trace, args, params):
--> 332     out = trace.process_primitive(self, map(trace.full_raise, args), params)
    333     return map(full_lower, out) if self.multiple_results else full_lower(out)
    334 

~/.local/lib/python3.7/site-packages/jax/core.py in process_primitive(self, primitive, tracers, params)
    710 
    711   def process_primitive(self, primitive, tracers, params):
--> 712     return primitive.impl(*tracers, **params)
    713 
    714   def process_call(self, primitive, f, tracers, params):

~/.local/lib/python3.7/site-packages/jax/_src/dispatch.py in apply_primitive(prim, *args, **params)
    113   compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
    114                                         **params)
--> 115   return compiled_fun(*args)
    116 
    117 # TODO(phawkins,frostig,mattjj): update code referring to

~/.local/lib/python3.7/site-packages/jax/_src/dispatch.py in <lambda>(*args, **kw)
    198                                     prim.name, donated_invars, False, *arg_specs)
    199   if not prim.multiple_results:
--> 200     return lambda *args, **kw: compiled(*args, **kw)[0]
    201   else:
    202     return compiled

~/.local/lib/python3.7/site-packages/jax/_src/dispatch.py in _execute_compiled(name, compiled, input_handler, output_buffer_counts, result_handler, has_unordered_effects, ordered_effects, kept_var_idx, has_host_callbacks, *args)
    893       runtime_token = None
    894   else:
--> 895     out_flat = compiled.execute(in_flat)
    896   check_special(name, out_flat)
    897   out_bufs = unflatten(out_flat, output_buffer_counts)

XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 23.64GiB (25386480000B) on device ordinal 0
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:   23.64GiB
              constant allocation:         0B
        maybe_live_out allocation:   23.64GiB
     preallocated temp allocation:         0B
                 total allocation:   47.29GiB
              total fragmentation:         0B (0.00%)
Peak buffers:
	Buffer 1:
		Size: 23.64GiB
		Entry Parameter Subshape: f32[1000,365,27,644]
		==========================

	Buffer 2:
		Size: 23.64GiB
		XLA Label: copy
		Shape: f32[1,1000,365,27,644]
		==========================
`

**Comment by pabloduque0** [comment]
Hello @giritatavarty-8451 !

Thanks for opening this one! That is one beefy dataset (for MMM standards) :)

Yes there is not much batching done at the moment so I would expect OOM errors for such a case. For multiple GPUs we would need to `pmap` things a bit. However I would expect things to be able to fit in an `A100`.

Let me look into this a bit and get back to you.

**Comment by pabloduque0** [comment]
Hey @giritatavarty-8451 !

So we would need to make a few changes to allow for batching or similar and that might take a bit.

In the meantime I want to check we cannot fix it through the current setup:
You would want to avoid the following flags that you have tried:
```
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] ='false'
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR']='platform'
```
So :
```
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] ='true'
# And not setting allocator.
```

Let me know if anything of that helps or not and we can try a few other options.

**Comment by giritatavarty-8451** [comment]
I tried with a 80GB GPU A100, it seemed to work - However, if i run more chains, it would fail. XLA_PYTHON_CLIENT_PREALLOCATE = false did not help much with low memory GPU. Finally, we have decided to chunk the problem (divide and conquer)  into independent multiple product groups and that seemed to reduce the geos by considerable margin and we are able to use commodity GPUs on the cloud.
