### ISSUE TITLE
Regarding the use of impressions in MMM

### ISSUE THREAD

**Issue by bart-vanvlerken** [google/lightweight_mmm#106]
I have a theoretical question about the use of exposure level metrics (such as impressions) in MMM. Since some of the models in LightweightMMM incorporate diminishing returns (channel saturation), does it make sense to use exposure level metrics as input? I was under the impression (no pun intended) that diminishing returns reflected on the relationship between spend and returns (be it impressions or sales) and NOT on the relationship between impressions and returns (such as sales)? I know it is possible to include both spend data and exposure level metrics in LightweightMMM, but would does including exposure level data work other than to calculate ROAS?

**Comment by pabloduque0** [comment]
Hello @bart-vanvlerken !

In short it is okay to use impressions as your media unit. After all impressions is a proxy and highly correlated with spend, so one can establish the diminishing returns between impressions and returns as well.

Hope it helps!

**Comment by bart-vanvlerken** [comment]
Thanks Pablo!
