### ISSUE TITLE
Baseline Contribution Error

### ISSUE THREAD

**Issue by smmalik98** [google/lightweight_mmm#107]
### Discussed in https://github.com/google/lightweight_mmm/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **smmalik98** November 20, 2022</sup>
I have been trying to plot the baseline media contribution but it has been failing since one of my media contribution has positive and negative values. This problem started when I reduced the number of columns. Initially my data had 7 media columns and 35 extra features with around 157 rows (weekly data). But now it has reduced to 5 media columns and 15 extra features. I have also added the screenshot of the error that I am getting. 
I need help in interpreting what is wrong with the model?
<img width="1690" alt="Screen Shot 2022-11-20 at 11 48 02 AM" src="https://user-images.githubusercontent.com/97324716/202917839-ae9ea69c-f3b3-41ac-adef-7acb85f6040e.png">
</div>

**Comment by pabloduque0** [comment]
Although I might need a bit more information it looks like one (or some) of your extra features have positive impact through some time followed by negative impact. I think this is not allowed by `seaborn` in a `stacked plot`.

Could you confirm that by removing the extra features it works correctly?

It might not necessarily mean anything is wrong with the model but this behaviour looks incompatible with what `seaborn` expects. We might need to look on a workaround for this scenarios.

**Comment by smmalik98** [comment]
The extra features come from economic, weather and covid data. I am trying to develop this model for a subscription product so it is expected that some features will definitely have positive and negative effect on the target variable but I am. not sure which one.  
How can I find the features that have such effects?

**Comment by smmalik98** [comment]
Thank you so much for quick responses. This was really helpful.
