### ISSUE TITLE
print_summary() interpretation

### ISSUE THREAD

**Issue by sataksipagat13** [google/lightweight_mmm#108]
Hi,

I have some cases like below in print_summary() output. I want to ask that for example coef_media[1],  I have not any divergence or high r_hat issue, but parameter std is so high compared to its mean. How can I interpret this ? Should this lower my confidence to model ? 
<img width="664" alt="image" src="https://user-images.githubusercontent.com/41327519/203718487-77757239-f82e-4861-8451-d6853e021de6.png">

**Comment by pabloduque0** [comment]
Hello @sataksipagat13 !

One will want to get low standard deviations in the posteriors but not necessarily in relation to the mean. A distribution can be centered around 0 and that does not mean it `std` should be 0.

I think is better to analyse the posterior plots and see if you see anything odd there.

Hope it helps!

**Comment by sataksipagat13** [comment]
Thanks for your answer Pablo. I have another question about prior multiplier. In the example notebook, you choose 0.15 as prior multiplier and it was explained as typical range in MMMs. I could not clearly understand that 'typicality'. Can you make it clear for me? Because as far as I understand from the code, prior selection is so crucial. I am looking for some heuristic for prior selection, maybe deriving prior by looking at data.

**Comment by pabloduque0** [comment]
Hello @sataksipagat13 !

In short you dont need to use the `0.15` as it applies to our mock data only. You might need to use also a factor but that will depend on your data.

We only use `0.15` so we get a reasonable baseline vs media contributions in the demo. That is what the "typicality" refers to, the ratio baseline vs media contribution.

Hope it helps!
