### ISSUE TITLE
Delay effect in hill adstock transformation

### ISSUE THREAD

**Issue by adavoli91** [google/lightweight_mmm#109]
Hi,

I'd like to know if it's possible to include the delay effect of the adstock transfomation on media data if the variable _transform_function_ in the definition of the model is set to _transform_hill_adstock_. 

Looking at the function _transform_hill_adstock_ of the script _models.py_ of the repository, it doesn't seem to be possible, as the delay effect is only included in the carryover transformation.

Thanks,
Alessandro

**Comment by pabloduque0** [comment]
Hello @adavoli91 !

Indeed `delay_effect` is a parameter of the `carryover`.

What are you trying to achieve?

**Comment by adavoli91** [comment]
Hi,

my interpretation of the paper was that hill-adstock is a combination of hill + adstock transofmations and that the latter is, in its most general form, given by a weighted sum where the weights contain the delay effect (i.e., the theta parameter).

If this is the case, I would expect the parameters of the delay effect (the theta's) to be in the hill-adstock transofmation as well and, as such, to be obtainable from the fitted model.

Did I misunderstand the paper?

Thanks,
Alessandro

**Comment by pabloduque0** [comment]
Hello @adavoli91 !

I think it is just a different naming from what you are referring.

The adstock parameter is refered as `lag_weight` and you can obtain it from the model posterior, as well as pass [custom priors for it](https://lightweight-mmm.readthedocs.io/en/latest/custom_priors.html#adstock).

Let us know if that is indeed what you were looking for.

**Comment by adavoli91** [comment]
Isn't lag_weight the parameter corresponding to what in the paper is referred to as _alpha_, i.e. the base of _alpha^((l-theta)^2)_, where "l" is the lag? Because, if that is the case, what I'd like to get is not _alpha_, but _theta_.

**Comment by pabloduque0** [comment]
By paper are you refering to [this one](https://research.google/pubs/pub46001/)?

So the formula you are referring to (if im understanding correctly you question) is for the `carryover` not for the `adstock`. If you want to use the carryover model you can just pass `model_name="carryover"` when instantiating the model.

For [custom priors for the carryover](https://lightweight-mmm.readthedocs.io/en/latest/custom_priors.html#carryover) you have the `ad_effect_retention_rate` (`alpha` in the paper) and `peak_effect_delay` (`theta` in the paper).

**Comment by adavoli91** [comment]
Yes, I'm referring to that paper.

I thought that the formula was for adstock as well, as in the paper it is indicated as _delayed adstock function_. Anyway, I guess from your answer that it is not possible to include the delay effect in the hill-adstock transformation. If this is the case, I am satisfied with your answer.

In any case, I suggest you to implement this possibility in the future if it's possible, as the authors talk explicitly of _delayed adstock_ (see, e.g., section 5).

Cheers,
Alessandro

**Comment by pabloduque0** [comment]
I think what you are referring to is the `carryover` indeed. Therefore those parameters are found in the `carryover` model. The `adstock` has a different parameter which can also be found in such model.

We'll try to make the documentation on this a bit more intuitive :)
