### ISSUE TITLE
plot_media_channel_posteriors running into an error

### ISSUE THREAD

**Issue by hammer-mt** [google/lightweight_mmm#11]
![image](https://user-images.githubusercontent.com/5264596/172358230-c01a0b10-feaa-49df-9ccb-ca2942fa5c5f.png)

I'm running into an error when trying the plot_media_channel_posteriors on the standard simulated data from the instructions. "IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed"

Here's my colab notebook: https://colab.research.google.com/drive/1S3V8T8CfIFaaGweySDyuQ4Jrqy8QnU1i?usp=sharing

**Comment by pabloduque0** [comment]
Hi Michael! Thanks for opening this one! And thanks for providing the colab.

I believe this is due to a missmatch of plotting underlying libraries and `lightweight_mmm`, we are now forcing at install time for the user to use the following versions of those libraries:

```
"arviz==0.11.2",
"matplotlib==3.3.4",
"seaborn==0.11.1"
```

If you upgrade lightweight_mmm it should install those be default. I see that you are then upgrading manually `matplotlib`, where you getting any other errors prior to that?

Let me know :)

**Comment by hammer-mt** [comment]
Oh wow thanks for the fast response, and for releasing this library, I've been hoping someone at Google would release something based off the various Bayesian MMM papers.

I can confirm it's working now I've upgraded.

FYI this was the error I ran into with matplotlib: https://stackoverflow.com/questions/64862818/cannot-import-name-png-from-matplotlib, but the upgrade solved this problem too.

One final thing I can't figure out is why the out of sample predictions are so bad on simulated data? Is it a scaling problem maybe? (same colab link)
![image](https://user-images.githubusercontent.com/5264596/172377723-1c14923b-b67d-4ebe-88b7-1d27f097e10b.png)

The reason I'm learning it is to build a course on it like I did with Facebook Robyn: https://app.vexpower.com/sim/can-we-try-facebook-robyn/. I'll let you know when it's live, hopefully tomorrow!

**Comment by hammer-mt** [comment]
That'd be great! 

The print_summary is there a few cells above, no divergences.
![image](https://user-images.githubusercontent.com/5264596/172417827-bc7cc1bf-d6fe-402d-a0fe-a19e9aab4f24.png)
![image](https://user-images.githubusercontent.com/5264596/172417903-2919dec0-6786-45bc-929e-e3d0485bdfe6.png)

**Comment by pabloduque0** [comment]
At a first glance I dont see anything wrong in your code. Let me try to reproduce elsewhere and get back to you.

**Comment by pabloduque0** [comment]
Okay so in this case you were fitting the model with the unscaled data, and then the model was acting weird when you passed scaled data.

If you train it on scaled data it should fix the error:
```
mmm.fit(media=media_data_train,
        extra_features=extra_features_train,
        total_costs=costs,
        target=target_train,
        number_warmup=1000,
        number_samples=1000,
        number_chains=2)
```

![Selection_041](https://user-images.githubusercontent.com/13575259/172481145-15d633ee-6b8e-4002-9321-049db83d2ec5.png)

Here is a copy of your notebook (although did not change anything after the plot that was not being displayed correctly): https://colab.research.google.com/drive/1sNckTk4jWKeLT8slwj_WyViz7rMl3eTF#scrollTo=cYHGD50YjQfK

**Comment by hammer-mt** [comment]
Awesome I very much appreciate your help on this!

**Comment by hammer-mt** [comment]
Hey just as a follow up, here's the course I made, it's free (just needs an email signup):
https://app.vexpower.com/sim/can-we-try-google-lightweightmmm/

Also I wrote a review of the project, I hope you find it useful feedback and please let me know if I've gotten anything wrong.
https://getrecast.com/google-lightweightmmm/

It's a really great library you've built! Thanks again for being so responsive.

**Comment by pabloduque0** [comment]
Hey @hammer-mt ! Let me give it a good read and get back to you, but at a first glance it looks super nice!

Thanks again for writing that up!

**Comment by hammer-mt** [comment]
Thanks awesome thanks for featuring!
