### ISSUE TITLE
valid JAX type issue while plotting

### ISSUE THREAD

**Issue by hellojungkook** [google/lightweight_mmm#111]
Hi
I am trying to plot the optimal budget allocation and I used the code below :

# Plot out pre post optimization budget allocation and predicted target variable comparison.
plot.plot_pre_post_budget_allocation_comparison(media_mix_model=mmm, 
                                                kpi_with_optim=solution['fun'], 
                                                kpi_without_optim=kpi_without_optim,
                                                optimal_buget_allocation=prices * solution.x, 
                                                previous_budget_allocation=prices * previous_media_allocation, 
                                                figure_size=(10,10))

however it constantly returns the below error

TypeError                                 Traceback (most recent call last)
Input In [118], in <cell line: 2>()
      1 # Plot out pre post optimization budget allocation and predicted target variable comparison.
----> 2 plot.plot_pre_post_budget_allocation_comparison(media_mix_model=mmm, 
      3                                                 kpi_with_optim=solution['fun'], 
      4                                                 kpi_without_optim=kpi_without_optim,
      5                                                 optimal_buget_allocation=prices * solution.x, 
      6                                                 previous_budget_allocation=prices * previous_media_allocation, 
      7                                                 figure_size=(10,10))

File ~/.local/lib/python3.10/site-packages/lightweight_mmm/plot.py:811, in plot_pre_post_budget_allocation_comparison(media_mix_model, kpi_with_optim, kpi_without_optim, optimal_buget_allocation, previous_budget_allocation, channel_names, figure_size)
    807 if not hasattr(media_mix_model, "trace"):
    808   raise lightweight_mmm.NotFittedModelError(
    809       "Model needs to be fit first before attempting to plot its fit.")
--> 811 previous_budget_allocation_pct = previous_budget_allocation / jnp.sum(
    812     previous_budget_allocation)
    813 optimized_budget_allocation_pct = optimal_buget_allocation / jnp.sum(
    814     optimal_buget_allocation)
    816 if channel_names is None:

File ~/.local/lib/python3.10/site-packages/jax/_src/numpy/reductions.py:216, in sum(a, axis, dtype, out, keepdims, initial, where, promote_integers)
    212 @_wraps(np.sum, skip_params=['out'], extra_params=_PROMOTE_INTEGERS_DOC)
    213 def sum(a: ArrayLike, axis: Axis = None, dtype: DTypeLike = None,
    214         out: None = None, keepdims: bool = False, initial: Optional[ArrayLike] = None,
    215         where: Optional[ArrayLike] = None, promote_integers: bool = True) -> Array:
--> 216   return _reduce_sum(a, axis=_ensure_optional_axes(axis), dtype=dtype, out=out,
    217                      keepdims=keepdims, initial=initial, where=where,
    218                      promote_integers=promote_integers)

    [... skipping hidden 2 frame]

File ~/.local/lib/python3.10/site-packages/jax/_src/api.py:3084, in _check_arg(arg)
   3082 def _check_arg(arg):
   3083   if not (isinstance(arg, core.Tracer) or _valid_jaxtype(arg)):
-> 3084     raise TypeError(f"Argument '{arg}' of type {type(arg)} is not a valid JAX type.")

TypeError: Argument 'discovery    0.023208
display      0.036849
youtube      0.039848
search       0.861380
shopping     0.038715
dtype: float32' of type <class 'pandas.core.series.Series'> is not a valid JAX type.

here is the code for the optimal/previous budget allocation

optimal_buget_allocation = prices * solution.x
optimal_buget_allocation
discovery    0.024865
display      0.039481
youtube      0.042694
search       0.865307
shopping     0.027653
dtype: float64

previous_budget_allocation = prices * previous_media_allocation
previous_budget_allocation
discovery    0.023208
display      0.036849
youtube      0.039848
search       0.861380
shopping     0.038715
dtype: float32

Thanks.

**Comment by pabloduque0** [comment]
Hello @hellojungkook 

Can you share the versions of the libraries you are using (matplotlib, lightweight_mmmm, ...) ? 

Where are you running this to get such error?

Thanks

**Comment by hellojungkook** [comment]
@pabloduque0 Hi!
Thank you for your reply.
My ldap is @jungkook so I can share more details regarding the data if you have a question. Data I've used is internal data. 

Here are the list of packages
Name: lightweight-mmm
Version: 0.1.6
Summary: Package for Media-Mix-Modelling
Home-page: https://github.com/google/lightweight_mmm
Author: Google LLC
Author-email: no-reply@google.com
License: Apache 2.0
Location: /usr/local/google/home/jungkook/.local/lib/python3.10/site-packages
Requires: absl-py, arviz, immutabledict, jax, jaxlib, matplotlib, numpy, numpyro, pandas, scipy, seaborn, sklearn, tensorflow
Required-by: 
Note: you may need to restart the kernel to use updated packages.


Name: matplotlib
Version: 3.6.2
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/local/google/home/jungkook/.local/lib/python3.10/site-packages
Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil
Required-by: arviz, lightweight-mmm, seaborn
Note: you may need to restart the kernel to use updated packages.

Name: numpyro
Version: 0.10.1
Summary: Pyro PPL on NumPy
Home-page: https://github.com/pyro-ppl/numpyro
Author: Uber AI Labs
Author-email: 
License: Apache License 2.0
Location: /usr/local/google/home/jungkook/.local/lib/python3.10/site-packages
Requires: jax, jaxlib, multipledispatch, numpy, tqdm
Required-by: lightweight-mmm
Note: you may need to restart the kernel to use updated packages.

Name: pandas
Version: 1.3.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: arviz, lightweight-mmm, seaborn, xarray
Note: you may need to restart the kernel to use updated packages.

**Comment by hellojungkook** [comment]
Hi @pabloduque0 
I just figured out the issue. Once I changed the type of the data using jnp.array, it worked just fine!
Thanks!
