### ISSUE TITLE
Hill and carryover transformations

### ISSUE THREAD

**Issue by kimbtowns** [google/lightweight_mmm#114]
Hi,

I recently discovered your library and I find it very interesting.

However, as far as I can see, the combination of hill transformation + carryover is not implemented (differently from hill + adstock). Do you plan to include it?

I think it could be very useful to combine lag and saturation effects.

Thanks,
Kimberly

**Comment by michevan** [comment]
Hi Kimberly, thanks a lot for the feedback! You're right that we don't currently implement a Hill + carryover model, and I don't think that's a short-term plan for us either. 

Just to be clear though, all three existing models in LMMM do offer combinations of lag and saturation effects. The adstock and carryover transformations are two different ways to model lag effects, and the Hill transformation models saturation effects. For the models without the Hill transformation, LMMM uses a simple exponential to model saturation instead. 

I recommend trying out all three models and seeing which one works best for your dataset!
