### ISSUE TITLE
AttributeError: 'CustomScaler' object has no attribute 'divide_by'

### ISSUE THREAD

**Issue by virithavanama** [google/lightweight_mmm#116]
I have loaded the model using load_model,
when trying to use 'find_optimal_budgets' with 
media_scaler = preprocessing.CustomScaler(divide_operation=jnp.mean)
target_scaler = preprocessing.CustomScaler(divide_operation=jnp.mean) 
I'm getting 'AttributeError: 'CustomScaler' object has no attribute 'divide_by'' error

**Comment by michevan** [comment]
Hi virithavanama!

If you're not already doing this, you need to make sure to run the fit() or fit_transform() method for these scalers. This is done at the bottom of the "Organising the data for modelling" section of the example Colabs. Please let me know if this helps!

Mike

**Comment by virithavanama** [comment]
I'm trying to use the saved model, to run the find_optimal_budgets;  so I won't have the input data to do fit or fit_transform

**Comment by virithavanama** [comment]
> Hi virithavanama!
> 
> If you're not already doing this, you need to make sure to run the fit() or fit_transform() method for these scalers. This is done at the bottom of the "Organising the data for modelling" section of the example Colabs. Please let me know if this helps!
> 
> Mike

I'm trying to use the saved model, to run the find_optimal_budgets; so I won't have the input data to do fit or fit_transform

**Comment by virithavanama** [comment]
is it possible to save the media scaler object, download and access it later?

**Comment by michevan** [comment]
That is possible, yes! The save_model() and load_model() functions should also work for saving the scaler objects and loading them in a different Colab

**Comment by virithavanama** [comment]
I have saved the model, can you help me how to access media scaler with load_model?

**Comment by michevan** [comment]
if you save your scaler with something like 
utils.save_model(media_scaler, file_path=os.path.join(OUTPUT_PATH, 'media_scaler'))

then you can later load it with
my_media_scaler = utils.load_model(file_path=os.path.join(OUTPUT_PATH, 'media_scaler'))

**Comment by virithavanama** [comment]
Thank you so much...this really helps when we just want to use the model at a later point without input data!
I recommend including this in the documentation and demo and if possible just saving these scalers directly when saving the mmm model.

**Comment by MDI3174** [comment]
On saving and loading "media_scalar" it throws the below error. Could anyone help to resolve?
![image](https://github.com/google/lightweight_mmm/assets/86763012/0f1d83fa-810a-43db-80dc-940987571a24)

**Comment by gittybobomber** [comment]
I have the same error
`AttributeError: This 'CustomScaler' has no attribute 'set_output'`
after saving
`utils.save_model(media_scaler, file_path="media_scaler.pkl")`
and
loading
`media_scaler = utils.load_model(file_path='media_scaler.pkl')`
How can I fix it?
