### ISSUE TITLE
How to set lag_weight prior distribution to Uniform?

### ISSUE THREAD

**Issue by steven-struglia** [google/lightweight_mmm#160]
Hello! I'd like to know how to set the prior distribution of the `lag_weight` parameter to a Uniform(low,high) for each of my media channels and feed it into custom_priors for `fit()`. How can I change it from Beta(c1,c0) to Uniform(low,high) for each media channel? I tried feeding it a list of distributions like so:
 
```
dists = np.array([numpyro.distributions.Uniform(low=0.2, high=0.7)]*24)
custom_priors = {'lag_weight': dists}
```
but it errors out with `TypeError: __init__() takes 3 positional arguments but 24 were given`

**Comment by michevan** [comment]
Thanks a lot for flagging this! I just wanted to share a link to our new "[support](https://github.com/google/lightweight_mmm#support)" section in the readme to give you some more information on how we can and cannot support such issues at the moment.
