### ISSUE TITLE
plot import error

### ISSUE THREAD

**Issue by Xiao-yun-Hu** [google/lightweight_mmm#162]
I'm trying to import plot using this commend on google colab: from lightweight_mmm import plot

but got this error:
initialization of _internal failed without raising an exception

Anyone knows why this happened?

**Comment by kingsj0405** [comment]
Hi :)
I get the same error.
How did you solve it?

**Comment by Xiao-yun-Hu** [comment]
Hi,

You could run this at the beginning 

!pip install --upgrade pip
!pip install --upgrade git+https://github.com/google/lightweight_mmm.git

!python -m pip uninstall numba
!pip install numba==0.56.3

and then restart run time

**Comment by kingsj0405** [comment]
@Xiao-yun-Hu
Thank you for the answer. Have a nice day :)
