### ISSUE TITLE
plot_response_curves and plot_prior_and_posterior do not work with custom lag_weight prior

### ISSUE THREAD

**Issue by slavakx** [google/lightweight_mmm#176]
Hi, 

when I provide custom priors for lag_weight in a hill_adstock model, 

plot_response_curves throws the following error:
![image](https://user-images.githubusercontent.com/6716523/220416056-bf942d08-acb6-4b16-9aef-b9918290d5e4.png)

plot_prior_and_posterior throws the following error:
![image](https://user-images.githubusercontent.com/6716523/220416211-930c7d19-90ab-4648-94df-67cee79fd256.png)

**Comment by steven-struglia** [comment]
Hi! Can you share what you assigned to `custom_priors`? 

Documentation for custom priors can be found here: https://lightweight-mmm.readthedocs.io/en/latest/custom_priors.html

Regarding changing the `lag_weight` parameter in `custom_priors`, you can do it like this:
```
c1 = np.array([2] * len(media_columns)
c1[7] = 1.5
c0 = np.ones(len(media_columns)
custom_priors = {'lag_weight': {'concentration1': c1, 'concentration0': c0}}
```
Keep in mind that the default distribution for `lag_weight` is a `dist.Beta(concentration1=2., concentration0=1.)`. If you want to change it to a different distribution, you must change the default distribution in `models.py` line 132.

**Comment by slavakx** [comment]
Hi, 
sure, here they are:

alpha = np.array([2.0] * len(media_channels))
beta = np.ones(len(media_channels))*4.0

alpha[0] = 3.0
beta[0] = 4.0

custom_priors = {'lag_weight': {'concentration1': alpha, 'concentration0': beta}}


the model summary is below:

![image](https://user-images.githubusercontent.com/6716523/220430275-857104bb-14da-4c04-b866-2cbb915b43a9.png)

**Comment by steven-struglia** [comment]
Interesting, so your `fit()` works and your parameters afterwards look reasonable by eye-check along with good/great `r_hat`'s. I'm lost lol.

**Comment by slavakx** [comment]
Exactly. These functions work without custom priors set

**Comment by slavakx** [comment]
Worked as described in #173
