### ISSUE TITLE
Example notebook

### ISSUE THREAD

**Issue by juanitorduz** [google/lightweight_mmm#2]
Hi! This project looks awesome! Thank you for sharing it 🚀 ! It would be great to have a concrete example maybe as a notebook (specially because to see the plots)? I have worked some simulation examples in with orbit's KTR model and pymc (see https://juanitorduz.github.io/orbit_mmm/ and https://juanitorduz.github.io/pymc_mmm/). Maybe I / we can extend this simulated examples in `lightweight_mmm`?

**Comment by pabloduque0** [comment]
Hi @juanitorduz ! Thanks for reaching out! That is a very good point, we are currently working on a few set of notebooks showcasing a end to end demo, plots, media optimisation and other features.

Im hoping to release the first one this week and the others will follow.

Although those notebooks aim to showcase the features available in the library we would love to see how the community uses it, so feel free to share with us any work that you do with `lightweight_mmm` and we can link it somewhere as well :)

**Comment by juanitorduz** [comment]
Cool! Looking forward! :)
