### ISSUE TITLE
Kpi is smaller than spend on response curve

### ISSUE THREAD

**Issue by MuhammedTech** [google/lightweight_mmm#213]
Hi,

Response curves' KPI is way smaller than the X axis which is spend but it should be the other way around considering that ROI and contribution are on point. This is really weird that I am spending more than I'm getting. The model i am using is hill_adstock
![Screen Shot 2023-06-02 at 11 29 44](https://github.com/google/lightweight_mmm/assets/61165055/0b6a6195-8f6e-4908-a36d-fabfe9268578)

My code: `plot.plot_response_curves(steps=52, media_mix_model=mmm, media_scaler=media_scaler, target_scaler=target_scaler, figure_size=(15,10))`

I have 5 features and more than 20 extra features.

This is the ROI
![Screen Shot 2023-06-02 at 11 32 48](https://github.com/google/lightweight_mmm/assets/61165055/45bcce62-157b-4ce2-b216-a311e513ff9c)

the problem is somewhat similar to Issue #51 
The author suggested an alternative solution, i am not sure if that solution would work for my case, tried, but failed to implement it.

**Comment by jannnnabi** [comment]
@MuhammedTech 
Hi~ Can I ask you something if you don't mind? You said you put in 20 extra features, but I wonder what you put in. If the target is order, can I also include data such as visit, revenue, and cart add?
