### ISSUE TITLE
Model prediction decomposition

### ISSUE THREAD

**Issue by adavoli91** [google/lightweight_mmm#223]
Hi,

I'm trying to decompose the model prediction into its components (trend, seasonality, etc.), and I'd have a couple of questions:

- in order to do that, I'm using the formulae in the documentation and the parameters which can be found in model.trace, as I didn't find the individual components already computed. Is that correct?
- if so, what is the meaning of the parameter model.trace['sigma']?
- once I obtained all the components, should I compare their sum with model.trace['mu']?

Thanks.

Cheers,
Alessandro

**Comment by becksimpson** [comment]
Heya, fellow MMM'er.
1. media_transformed, is pre-computed using numpyro deterministic function, which appears in the trace, so to get individual media contributions you can use: **plot._calculate_media_contribution**. There are a number of additional steps used by plots.create_media_baseline_contribution_df, (which generates the stacked bar charts for media contribution + baseline), that handles cases of negative baseline, clipping it to 0, then rescaling the values to the original prediction total. This is superfluous, in a lot of cases, if you have high baseline offset.
If you want seasonality/trend components, the quickest solution is to multiply the trace coefficients by the stored values observed in the training data. This is something like what I've done:
n_samples here is your training data length, mc_samples, is your monte carlo num_samples
```
from lightweight_mmm_parent.lightweight_mmm.models import _COEF_TREND, _COEF_SEASONALITY, _EXPO_TREND, _GAMMA_SEASONALITY, _WEEKDAY
from lightweight_mmm_parent.lightweight_mmm.media_transforms import calculate_seasonality
from lightweight_mmm_parent.lightweight_mmm.plot import _calculate_media_contribution
media_contribs = _calculate_media_contribution(mmm)
extra_features_contribs = jnp.einsum(
    "tf, sf->stf",
    mmm._extra_features,
    mmm.trace[_COEF_EXTRA_FEATURES]
)
trend = mmm.trace[_COEF_TREND].reshape(1, -1) * np.arange(n_samples).reshape(-1, 1) ** mmm.trace[_EXPO_TREND]
dow_seasonality = mmm.trace[_WEEKDAY][:, (np.arange(n_samples) % 7)]
year_seasonality = np.concatenate([
    calculate_seasonality(
        number_periods=n_samples,
        degrees=mmm._degrees_seasonality,
        frequency=mmm._seasonality_frequency,
        gamma_seasonality=mmm.trace[_GAMMA_SEASONALITY][i]
    ).reshape(1, -1)
    for i in range(mc_samples)
], axis=0)
```
2. I believe the sigma is meant to represent aleatoric uncertainty, uncertainty inherent in natural phenomenon, where for any given x input, there may be a normal distribution of y responses. This is in contrast to the distributions for the model parameters such as exponent etc, which model the epistemic uncertainty, that arises from the lack of knowledge around the system you wish to model.
3. Yes, take the mean across samples of all component samples you produce, and ensure that they sum to model.trace['mu']
You may want to inverse transform, the calculated contributions using the target scaler if you used one, and want it in the original scale. This will be a lil finickity as your scaler will expect 1D data.

**Comment by adavoli91** [comment]
Thanks a lot!
