### ISSUE TITLE
Feature Names

### ISSUE THREAD

**Issue by jenowen** [google/lightweight_mmm#228]
Hello. Not really an issue as such but wondered if anyone had any tips. When reviewing outputs such as the print_summary I would love to be able to rename the features so it's 100% clear. If this is not possible can I at least confirm that they're in the same order as the columns in the original 'extra_features' array?
Thanks.

**Comment by becksimpson** [comment]
I have not seen an easy/quick way to accomplish this, as the LightweightMMM uses internal pyro pyro.infer.mcmc.util.print_summary.
I have always treated all extra features, media features as order pre-serving, and have no reason to believe this is not the case.

**Comment by jenowen** [comment]
Thanks for your help
