### ISSUE TITLE
Pip install doesn't work 

### ISSUE THREAD

**Issue by Navatso** [google/lightweight_mmm#26]
pip install gives dependency error:

ERROR: Cannot install lightweight-mmm==0.1.1, lightweight-mmm==0.1.2 and lightweight-mmm==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
lightweight-mmm 0.1.3 depends on jaxlib>=0.3.0
lightweight-mmm 0.1.2 depends on jaxlib>=0.3.0
lightweight-mmm 0.1.1 depends on jaxlib>=0.3.0

To fix this you could try to:

loosen the range of package versions you've specified
remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

I have tried pip installing the package into multiple new conda environments with different python versions from 3.6 to 3.9, none worked.

**Comment by pabloduque0** [comment]
Hello @Navatso ! Thanks for reporting this.

By the looks of the error, I think you might be trying to install it on windows. The support of JAX for windows is very limited so I would recommend installing it on Linux or using Colaboratory if you dont have access to a linux system.

Let me know if you are getting this error on Linux and I will dig a bit on this one.

**Comment by pabloduque0** [comment]
@Navatso great to hear!
