### ISSUE TITLE
ImportError: cannot import name 'Protocol' from 'typing'

### ISSUE THREAD

**Issue by chmstimoteo** [google/lightweight_mmm#35]
When running the demo notebook, after `pip3 install` the package from github, we face an `ImportError`.

# Import the relevant modules of the library
from lightweight_mmm import lightweight_mmm

[/usr/local/lib/python3.7/dist-packages/lightweight_mmm/models.py](https://localhost:8080/#) in <module>()
     23 """
     24 
---> 25 from typing import Any, Dict, Mapping, MutableMapping, Protocol, Optional, Sequence, Union
     26 
     27 import immutabledict

ImportError: cannot import name 'Protocol' from 'typing' (/usr/lib/python3.7/typing.py)

I could also see your github actions CI job failing for the same reason.

**Comment by pabloduque0** [comment]
@chmstimoteo should be fixed now! Let me know if you still running into errors.
