### ISSUE TITLE
Example failed - unexpected keyword argument in fit

### ISSUE THREAD

**Issue by nie-moviestarplanet** [google/lightweight_mmm#38]
Hello,

I'm running [this example](https://github.com/google/lightweight_mmm/blob/main/examples/simple_end_to_end_demo.ipynb) on a Databricks cluster (Runtime 10.4LTS, Python 3.8.10) and I'm getting the following issue when running fit:

```
mmm.fit(
    media=media_data_train,
    media_prior=costs,
    target=target_train,
    extra_features=extra_features_train,
    number_warmup=number_warmup,
    number_samples=number_samples,
    seed=SEED)
```

```
TypeError: fit() got an unexpected keyword argument 'media_prior'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-420949> in <module>
      1 # For replicability in terms of random number generation in sampling
      2 # reuse the same seed for different trainings.
----> 3 mmm.fit(
      4     media=media_data_train,
      5     media_prior=costs,

TypeError: fit() got an unexpected keyword argument 'media_prior'
```

**Comment by pabloduque0** [comment]
I think you might be using the new notebook with an older version of the library. Updating should fix it but let me know if it doesnt

**Comment by FedericoRaimondi** [comment]
I have the same issue as the expected keyword argument is still `total_costs`.
I am quite sure I'm using the latest version as I run:
`pip install --upgrade git+https://github.com/google/lightweight_mmm.git`

Also checked version running and returns '0.1.4'.

**Comment by Lei246** [comment]
Hi team, I have a similar issue with the TypeError: fit() got an unexpected keyword argument 'custom_priors'. Is "custom_priors" renamed to something else? Thanks!

**Comment by pabloduque0** [comment]
Hello @Lei246 @FedericoRaimondi @nie-moviestarplanet !

Unfortunately I am not able to replicate your error, although some of you have already tried, could you please retry the following?

1. Make sure you are updated to the github version if you are using the latest github notebook:
`pip install --upgrade git+https://github.com/google/lightweight_mmm.git`
2. Make sure you restart your `jupyter notebook` / `colab` kernel after updating the library.

If the error persists let me know.

**Comment by Lei246** [comment]
Hi, @pabloduque0 , my problem is solved after your steps. Thanks so much for your help!

**Comment by FedericoRaimondi** [comment]
I tried again, but I think this might be a Databricks related issue. On Colab is working just fine.
Somehow it still has a older version of the functions even if the library is up to date.

**Comment by FedericoRaimondi** [comment]
An update on this issue. Somehow the library was not updated to the last version in the cluster. Now I'm able to see the lastest .fit arguments.
