### ISSUE TITLE
`media_prior` with impressions only (unknown spend) 

### ISSUE THREAD

**Issue by PhilippeMoussalli** [google/lightweight_mmm#54]
Hello,

First of all, thank you for open-sourcing such an amazing library !

I have some question regarding the model that I hope you can help me with :)

I'm considering running lightweights mmm on a dataset that only comprises of different channels with their impressions (no channel costs included). My end goal is to use get an estimate on the the media effects of each channel (I don't need to generated the ROI estimates). 

My question is, would it be possible to conduct this sort of analysis without including the spend for each channel? I only have impressions with no costs but I know that spend is an obligatory prior in `mmm.fit` (`media_prior`).

In theory this should be possible since the three different marketing approach (ad-stock, hill_adstock and carryover) can be modelled based on spend or impressions as mentioned in the [docs](https://lightweight-mmm.readthedocs.io/en/latest/models.html#:~:text=Media%20Channels%20(for%20the%20carryover%20model))

Thank you in advance for your response.

**Comment by pabloduque0** [comment]
Yes you can generate the response curve normally and either provide no prices or prices of 1. Although labels will say spend, in your case it will be impressions.
