### ISSUE TITLE
Weird MAPE values 

### ISSUE THREAD

**Issue by virithavanama** [google/lightweight_mmm#56]
Hi Team,

1. I'm using the channel's cost as the media data and after training all the r_hat values are less than 1.1 and r2 score is 0.95, the prediction seems to be good but the MAPE value is weird as shown in the figure. Am I missing something?
![Screen Shot 2022-08-23 at 5 11 25 PM](https://user-images.githubusercontent.com/89505409/186266718-8b637bd5-8a4a-4d65-b897-a9e87d173cba.png)

2. Can I use impressions as the extra features?

Thanks!

**Comment by pabloduque0** [comment]
Hello @virithavanama !

If you are using spend as your media unit there is no need to include impressions. You can use either one but there is generally no benefit in having both.

With regards to the MAPE, I see some values are very close to 0 in your target, that can cause MAPE to give some very high values. It is one of the issues of MAPE.

**Comment by virithavanama** [comment]
Hi Pablo,
Thank you so much for your response. 
1. plot_media_baseline_contribution_area_plot is throwing an error saying it has both positive and negative values
2. When trying to run find_optimal_budgets for one year with last year's budget, it's saying the given budget is more than optimized.
Thanks in advance

**Comment by pabloduque0** [comment]
Hello @virithavanama !

1. Can you show here the stacktrace and the error you are getting?
2. One year might be too long term for optimization (not that it cant be done, but results might need a bit more carefulness). Can you show the pre/post optimization plot?

**Comment by virithavanama** [comment]
1. ValueError: When stacked is True, each column must be either all positive or all negative. Column 'PublisherDirect_x contribution' contains both positive and negative values

**Comment by pabloduque0** [comment]
@yukaabe Could you take a look at this error? @virithavanama could you provide a colab or similar that reproduces the error? It can be with mock data.

For this one yes, you can get the [dataframe for it](https://lightweight-mmm.readthedocs.io/en/latest/api.html#lightweight_mmm.plot.create_media_baseline_contribution_df).

**Comment by virithavanama** [comment]
Hi Pablo,
Thank you so much for your response.
Sorry, I cannot provide the notebook because we are working with client data.
Regarding the CSV/data frame, I meant for all the plots not just the baseline plot

**Comment by pabloduque0** [comment]
No, at the moment all plots do not give the output data by default. Although it is something that we have considered.
