### ISSUE TITLE
Installing lightweight_mmm

### ISSUE THREAD

**Issue by chsheth** [google/lightweight_mmm#57]
Hi, I get the following error when I install the packages. I am using anaconda terminal to run these commands. Can you please advise? Thank you.

----
(base) PS C:\Users\csheth> pip install lightweight_mmm
Collecting lightweight_mmm
  Using cached lightweight_mmm-0.1.5-py3-none-any.whl (63 kB)
Collecting matplotlib==3.3.4
  Using cached matplotlib-3.3.4-cp39-cp39-win_amd64.whl (8.5 MB)
Collecting seaborn==0.11.1
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting absl-py
  Using cached absl_py-1.2.0-py3-none-any.whl (123 kB)
Requirement already satisfied: pandas>=1.1.5 in c:\users\csheth\anaconda3\lib\site-packages (from lightweight_mmm) (1.3.4)
Requirement already satisfied: numpy>=1.12 in c:\users\csheth\anaconda3\lib\site-packages (from lightweight_mmm) (1.21.5)
Requirement already satisfied: scipy in c:\users\csheth\anaconda3\lib\site-packages (from lightweight_mmm) (1.7.1)
Collecting lightweight_mmm
  Using cached lightweight_mmm-0.1.4-py3-none-any.whl (60 kB)
Collecting frozendict
  Using cached frozendict-2.3.4-cp39-cp39-win_amd64.whl (35 kB)
Collecting lightweight_mmm
  Using cached lightweight_mmm-0.1.3-py3-none-any.whl (53 kB)
  Using cached lightweight_mmm-0.1.2-py3-none-any.whl (48 kB)
Collecting tensorflow==2.5.3
  Downloading tensorflow-2.5.3-cp39-cp39-win_amd64.whl (428.3 MB)
     ------------------------------------- 428.3/428.3 MB 1.3 MB/s eta 0:00:00
Requirement already satisfied: arviz in c:\users\csheth\anaconda3\lib\site-packages (from lightweight_mmm) (0.11.2)
Requirement already satisfied: seaborn in c:\users\csheth\anaconda3\lib\site-packages (from lightweight_mmm) (0.11.2)
Collecting lightweight_mmm
  Using cached lightweight_mmm-0.1.1-py3-none-any.whl (41 kB)
  Using cached lightweight_mmm-0.1.0-py3-none-any.whl (40 kB)
Collecting jax>=0.2.21
  Using cached jax-0.3.16.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
**ERROR:** Cannot install lightweight-mmm==0.1.0, lightweight-mmm==0.1.1, lightweight-mmm==0.1.2, lightweight-mmm==0.1.3, lightweight-mmm==0.1.4 and lightweight-mmm==0.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    lightweight-mmm 0.1.5 depends on jaxlib>=0.3.14
    lightweight-mmm 0.1.4 depends on jaxlib>=0.3.14
    lightweight-mmm 0.1.3 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.2 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.1 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.0 depends on tensorflow==2.4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**ERROR:** ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------

**Comment by pabloduque0** [comment]
Hi @chsheth 
By the looks of the paths it looks like you are trying to install it on Windows.

You can take a look at this [issue on JAX](https://github.com/google/jax/issues/438) to install JAX first and then you can go ahead to installing LMMM. However I highly recommend to try using a Linux machine or Colab if you dont have access to one.

**Comment by mjtriggs** [comment]
Just commenting as I had the same issue yesterday. I resolved by using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) on my Microsoft machine.

**Comment by chsheth** [comment]
> Hi @chsheth By the looks of the paths it looks like you are trying to install it on Windows.
> 
> You can take a look at this [issue on JAX](https://github.com/google/jax/issues/438) to install JAX first and then you can go ahead to installing LMMM. However I highly recommend to try using a Linux machine or Colab if you dont have access to one.

Thank you @pabloduque0, @mjtriggs. I used Colab and it worked and I believe for Windows, wsl might work as mjtriggs indicated.

**Comment by chsheth** [comment]
Thank you @pabloduque0, @mjtriggs. I used Colab and it worked and I believe for Windows, wsl might work as mjtriggs indicated.
