### ISSUE TITLE
Errors when running code notebook

### ISSUE THREAD

**Issue by chsheth** [google/lightweight_mmm#58]
As I run your code on Google colab, I noticed two bugs, possibly --
1. In mmm.fit(....), it looks like 'total costs' parameter is not available - does it need to be replaced by 'media_prior'?
mmm.fit(
    media=media_data_train,
    #total_costs=costs,
    media_prior=costs,
    target=target_train,
    extra_features=extra_features_train,
    number_warmup=2000,
    number_samples=2000,
    number_chains=2)

2. Towards the end of the notebook, where code cells have the code below have errors when run. It says "'tuple' object has no attribute 'x'". Here are the code cells -

#both values should be almost equal
budget, jnp.sum(solution.x * prices)
#&&&
for x in range(len(solution.x)):
    share = round(solution.x[x] / jnp.sum(solution.x * prices)*100, 2)
    print(channel_names[x], ": ", share, "%")

Not sure, but I believe, these cells need to be replaced by,
s = solution[2]
budget, jnp.sum(s * prices)
#&&&
for x in range(len(s)):
    share = round(s[x] / jnp.sum(s * prices)*100, 2)
    print(channel_names[x], ": ", share, "%")

Please advise. Thanks.

**Comment by pabloduque0** [comment]
I think you might be using an older notebook. Downloading the current notebook on github should solve both issues

**Comment by chsheth** [comment]
> I think you might be using an older notebook. Downloading the current notebook on github should solve both issues

Will do, thanks!
