### ISSUE TITLE
error for install package lightweight_mmm from linux system

### ISSUE THREAD

**Issue by sugardove** [google/lightweight_mmm#60]
ERROR: Cannot install lightweight-mmm==0.1.0, lightweight-mmm==0.1.1, lightweight-mmm==0.1.2, lightweight-mmm==0.1.3, lightweight-mmm==0.1.4 and lightweight-mmm==0.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    lightweight-mmm 0.1.5 depends on jaxlib>=0.3.14
    lightweight-mmm 0.1.4 depends on jaxlib>=0.3.14
    lightweight-mmm 0.1.3 depends on jax>=0.3.0
    lightweight-mmm 0.1.2 depends on tensorflow==2.5.3
    lightweight-mmm 0.1.1 depends on tensorflow==2.5.3
    lightweight-mmm 0.1.0 depends on jax>=0.2.21

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by pabloduque0** [comment]
Hi @sugardove !

Could you share the details of your system? What pip version as well?

**Comment by sugardove** [comment]
I have attached pip version below,
Name: pip
Version: 21.3.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
best,

**Comment by pabloduque0** [comment]
Hello! Im unable to reproduce this on pip 21.3.1.

Could you provide your OS, os version and python version as well?

**Comment by sugardove** [comment]
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Python 3.6.10

**Comment by pabloduque0** [comment]
@sugardove thank you for providing that!

At the moment we are supporting python `3.7`, `3.8`, `3.9` and `3.10` so I would suggest upgrading to any of those versions. 

Hope it helps!

**Comment by sugardove** [comment]
thanks, I will upgrade soon, best.
