### ISSUE TITLE
.predict vs .trace

### ISSUE THREAD

**Issue by sv09** [google/lightweight_mmm#64]
Hi Team,

What is the difference between '.predict' and '.trace["mu"]'? Below are the plots after running both -

1. prediction = mmm.predict(
    media=media_data,
    extra_features=extra_features,
    target_scaler=target_scaler
    )
    prediction_mean = prediction.mean(axis=0)

   plt.figure(figsize=(8,7))
   plt.plot(x, targ, label='Actual') --> targ is the actual target value in the data
   plt.plot(x, prediction_mean, label='Predicted')
   plt.legend()

   
<img width="500" alt="mmm_predict" src="https://user-images.githubusercontent.com/38870742/189139685-8eec95c2-1430-48af-b66a-4840756c2bdb.png">

   **np.sum(prediction_mean) = 24816.469**

2. pred = mmm.trace["mu"]
    predictions = target_scaler.inverse_transform(pred)
    pred_mean = predictions.mean(axis=0)

    plt.figure(figsize=(8,7))
    plt.plot(x, targ, label='Actual')
    plt.plot(x, pred_mean, label='Predicted')
    plt.legend()

   
<img width="500" alt="mmm_trace" src="https://user-images.githubusercontent.com/38870742/189140283-0776a722-8ad7-4060-8eb0-15d3a96c066f.png">

   **np.sum(pred_mean) = 43999.086**

The 'predicted' line in both plots have similar trend with the 'actual' line, however, with mmm.predict(), the predicted values have an offset, whereas,  with mmm.trace["mu"] that offset is not present - both predicted and actual lines are aligned.

Also, the sum of predicted values returned by mmm.predict and mmm.trace["mu"] are different. 
In my case, the sum of predicted values returned by mmm.trace["mu"] is close to the sum of actual target values in the data. Why is mmm.predict() not giving values close to the actual target values? 

It will be helpful to get a clarity on this.

Thank you!

**Comment by pabloduque0** [comment]
Hello @sv09 ! Great question!

The main difference is that `predict` assumes the prediction is made for data after the training period and therefore will use the lagging from the training data, whereas `.trace["mu"]` will start with lagging 0.

Essentially if you want the predictions from the training data `.trace["mu"]` should be what you are looking for, and if you want to run predictions after the training period, `predict` is there for you.

Hope that helps!

**Comment by sv09** [comment]
Hi @pabloduque0, thank you for that clarification! 
I'm using the entire data for training/prediction and budget allocation. In the budget allocation function, I think mmm.predict is used which makes 'kpi_without_optim' not match with the actual target value. 
So, in this case, instead of setting 'kpi_without_optim' argument with the value returned by 'optimize_media.find_optimal_budgets', should I set it with the actual target value from my data?

Replace 'kpi_without_optim' in the function below -

plot.plot_pre_post_budget_allocation_comparison(media_mix_model=mmm, 
                                                kpi_with_optim=solution['fun'], 
                                                kpi_without_optim=**kpi_without_optim**,
                                                optimal_buget_allocation=optimal_buget_allocation, 
                                                previous_budget_allocation=previous_budget_allocation, 
                                                figure_size=(12,10),
                                                channel_names=channel_names) 

with -

plot.plot_pre_post_budget_allocation_comparison(media_mix_model=mmm, 
                                                kpi_with_optim=solution['fun'], 
                                                kpi_without_optim= **-1x(total actual target value from the data)**,
                                                optimal_buget_allocation=optimal_buget_allocation, 
                                                previous_budget_allocation=previous_budget_allocation, 
                                                figure_size=(12,10),
                                                channel_names=channel_names) ?

**Comment by pabloduque0** [comment]
@sv09 how many `n_time_periods` are you optimising for and how many weeks did you training data have?

**Comment by sv09** [comment]
n_time_periods = 105 (weeks). The training data also has 105 weeks of data.

**Comment by pabloduque0** [comment]
Then my next guess is the budget. What budget are you passing to the optimisation? and what would be the total budget of the training data (if we made the equivalent calculation)?

**Comment by sv09** [comment]
I'm giving budget = 1337057.4 to 'optimize_media.find_optimal_budgets', and the total budget of the training data  = 1306110.91

**Comment by pabloduque0** [comment]
Thanks for your input, let me investigate this one and get back to you.

**Comment by pabloduque0** [comment]
@sv09 Im trying to replicate the behaviour with mock data and I am unable to run into the same big discrepancies.

Optimising for the total period of data gives me a difference of 1.5% when including the extra features and around ~3% when not including them. Which we can attribute to the lagging.

The next thing that I can think of is that you have highly influential extra features which you might have not included in the optimisation. Could that be the case?

If that is not the case, could you try to reproduce in a colab with mock data you can send my way?

**Comment by sv09** [comment]
Thank you @pabloduque0 for that! Yes, i didn't include extra features in optimisation. I'll include that and see how the results are, and let you know.

**Comment by sv09** [comment]
I ran the budget optimization with extra features, and now "pre optimization predicted target" value is much closer to the actual target value. However, if I use extra features for optimization, I have to use  n_time_periods = the number of weeks in the training data/extra features (since I'm using the whole data for training), else I get an error - "TypeError: add got incompatible shapes for broadcasting:". I was wondering if there was any way to include extra features while being able to use varying n_time_periods for budget optimization.

**Comment by pabloduque0** [comment]
Okay I think at this point is more about what do you want to optimise and how you want to do it. My suggestion of adding the extra features only comes from the expectation that pre optimisation predicted target should match historic target. Generally you can optimise without extra features, they will only affect the the absolute value of the predictions but will not alter  the media mix (they are only additive).

In reality when it comes to optimisation you would either estimate your extra features (if possible) or not include them, after all what you are looking at will be the media optimisation itself, the absolute value predicted by the optimisation is not what we are really focusing as the output of the optimisation, if the model has a decent fit, those values will be within a reasonable ballpark.

Therefore when estimating your extra features (again, if possible) you can estimate them of the length you want to optimise for.

Hope it helps.

**Comment by sv09** [comment]
Thanks a lot @pabloduque0, that helps!
