### ISSUE TITLE
plot_model_fit incompatible shapes for broadcasting

### ISSUE THREAD

**Issue by ledmaster** [google/lightweight_mmm#67]
Hi

While trying to plot the model fit for any new data I ran into the following issue:

![image](https://user-images.githubusercontent.com/9610024/190430109-a52cbb6d-4a8d-43f4-9cf8-2969c731a8d2.png)

The problem seems to be inside the arviz R2 function.

![image](https://user-images.githubusercontent.com/9610024/190430240-6ceb2ac5-9ba2-412d-b343-d8018a28c352.png)

This is the code that causes the error:

`plot.plot_model_fit(mmm, target_scaler=target_scaler)`

Maybe it's missing a transpose somewhere?

Thanks!

**Comment by ArezooSamimi** [comment]
Hello, 

The target input should be in shape (83,). This causes the error. 

Arezoo

**Comment by ledmaster** [comment]
@ArezooSamimi thanks! Completely missed it.

Will leave this open in case the devs want to take a look into adding a "squeeze" somewhere.

**Comment by pabloduque0** [comment]
Thanks for the issue @ledmaster and thanks @ArezooSamimi for the correct answer here :)

I am a bit reluctant to add a squeeze in the scaler as it actually works slightly differently for the media data. It might actually be okay bit need to give this one another thought, will close for now and we can re-open if necessary.
