### ISSUE TITLE
plot_pre_post_budget_allocation_comparison error with Geo data

### ISSUE THREAD

**Issue by virithavanama** [google/lightweight_mmm#69]
I running the MMM with 2 channels and 10 geo locations. Model has mean R2 score of 98, r_hat values <1.1
But when running plot_pre_post_budget_allocation_comparison, its giving me below error:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/89505409/190691053-cccbab8a-6c6f-4715-a02b-9385f92c49fb.png">
Also plot_media_baseline_contribution_area_plot is giving below error:
<img width="1153" alt="Screen Shot 2022-09-16 at 10 00 46 AM" src="https://user-images.githubusercontent.com/89505409/190691288-fc841206-31aa-4e14-b8c0-70fcceb72229.png">

**Comment by pabloduque0** [comment]
@virithavanama can you post the screenshot of the full stack trace in both cases? (Click to expand all frames). That would help us to spot what is going on.

**Comment by virithavanama** [comment]
plot_pre_post_budget_allocation_comparison:
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/89505409/190700908-ed2a1141-2cc0-4089-b166-71b5c87d0735.png">
plot_media_baseline_contribution_area_plot:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/89505409/190701081-2266bcd0-fbad-415e-9524-4c610402e63b.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/89505409/190701115-f51dceb1-2add-4629-a726-176143083900.png">

**Comment by pabloduque0** [comment]
Can you share the shapes of:
- mmm.media
- optimal_budget_allocation
- previous_budget_allocation

And the length of mmm.media_names

Thanks!

**Comment by virithavanama** [comment]
mmm.media -> (195, 2, 10)
optimal_budget_allocation -> (2,)
previous_budget_allocation -> (2,)
mmm.media_names -> (20,)

**Comment by pabloduque0** [comment]
Did you provide media_names directly?

If so, you only need to provide a list of length n_channels we will add geo suffix/labeling for plots.

**Comment by virithavanama** [comment]
didnt give media names at all:
plot.plot_media_baseline_contribution_area_plot(media_mix_model=mmm,
                                                target_scaler=target_scaler,
                                                fig_size=(30,10))

# Plot out pre post optimization budget allocation and predicted target variable comparison.
plot.plot_pre_post_budget_allocation_comparison(media_mix_model=mmm, 
                                                kpi_with_optim=solution['fun'], 
                                                kpi_without_optim=kpi_without_optim,
                                                optimal_buget_allocation=optimal_buget_allocation, 
                                                previous_budget_allocation=previous_budget_allocation,
                                                figure_size=(10,10))

**Comment by virithavanama** [comment]
Thank you, removing the media_names solved the issue!
