### ISSUE TITLE
find_optimal_budgets geo level

### ISSUE THREAD

**Issue by virithavanama** [google/lightweight_mmm#73]
Hi Team,

When I use Geo level data im getting find_optimal_budgets at channel level. Is there a way we can get this at geo level?

**Comment by pabloduque0** [comment]
At the moment optimisation is provided at channel level always, this is mainly due that bounds can be very tricky to use at geo level and the actual shifts of channel budget between geos at an operational level is something not what it is desired by the user.

We assume the average ratios between geos seen in the historical data and apply optimisation at channel level using such ratio.

It is something we can add for sure, but it is also not in our most immediate pipeline (unless there is a lot of demand for it).

**Comment by virithavanama** [comment]
so, can I use the preoptimization budget ratios of goe's and apply to post opt budget and get geo level post opt budget?

**Comment by pabloduque0** [comment]
1.  Yes! Feel free to check how the ratios are calculated in the code to replicate.
2. Not sure what you mean by this one. Could you explain further?

**Comment by virithavanama** [comment]
Hi @pabloduque0,

I couldn't find the ratios logic, can you please help me ?

**Comment by pabloduque0** [comment]
Ratios can be calculated with something like the folloiwng:
```
average_per_time = media_mix_model.media.mean(axis=0)
geo_ratio = average_per_time / jnp.expand_dims(average_per_time.sum(axis=-1), axis=-1)
```

**Comment by rio-0217** [comment]
Hi @pabloduque0,
I saw your great discussion, but I have some questions regarding this.
First, is the calculating logic you introduced above just for getting ratios at pre-optimization?
Moreover, it seems that the function `find_optimal_budgets` in the current version cannot consider the custom budget ratio of each geo at pre-optimization. Is my understanding correct?

Thank you.

**Comment by pabloduque0** [comment]
Hello @rio-0217 !
Yes, the logic is for calculating historical average ratio between geos.
That is correct! `find_optimal budgets` currently does not support custom "geo ratios" although that is something we could add.

**Comment by rio-0217** [comment]
Hello @pabloduque0,
Understood. I appreciate your kind reply.
Then I wonder if we can just add `geo_ratio` in the `find_optimal_budgets` function as a new argument, we can conduct optimization with custom geo_ratios. Is that make sense?
