### ISSUE TITLE
Question about fit parameters

### ISSUE THREAD

**Issue by adavoli91** [google/lightweight_mmm#84]
Hi,

I recently started using your library, and I'd like to ask you about some parameters of the fit method. In particular, can you tell me what is the meaning of the following parameters and what is the best practice, if any, for assigning a value to them?
- number_warmup
- number_samples
- number_chains

Thanks,
Alessandro

**Comment by pabloduque0** [comment]
Hello @adavoli91 !

Some high level overview of the parameters below, but if you are unfamiliar with bayesian inference maybe reading how sampling is done might give you more info about it.

- number_warmup: Number of warm up samples (these wont be in the trace) 
- number_samples: Number of samples during sampling (these will be the ones in your trace)
- number_chains: Number of chains to sample ("mostly" used for convergence checks). 

They are tight to how long your model needs to sample for until convergence. If your model is converging well there is no need to increase much the number of samples.  Also the more you increase any of these parameters the longer it will take for your model to train.

To give you some hints for MMM size data generally something along the following lines should suffice (although it will still depend on each scenario and data):

- number_warmup [1000, 4000]
- number_samples [1000, 6000]
- number_chains [2, 8]

**Comment by adavoli91** [comment]
Thanks a lot for your answer!
