### ISSUE TITLE
Bug in function calculate_seasonality()?

### ISSUE THREAD

**Issue by finn-stein** [google/lightweight_mmm#91]
Dear lightweight_mmm Team

First of all thanks a lot for this great package. It really solves a lot of problems that I see in common MMM approaches.
I think I stumbled upon a small bug when digging into the package that I want to share here. 

In `media_transfomrs.py` => `calculate_seasonality()` the degrees_range is initialized with:
`degrees_range = jnp.arange(degrees)` 

This results in Device Array of: 
`DeviceArray([0, 1], dtype=int32)`

If I get the maths right, this will always result in a constant for the 1st degree of seasonality, rather than a wave shape. As we are using priors, that doesn't necessarily break the model, but probably isn't intentional. 

```
inner_value = seasonality_range * 2 * jnp.pi * degrees_range / frequency
 season_matrix_sin = jnp.sin(inner_value)
 season_matrix_cos = jnp.cos(inner_value)

```

I hope this is helpful. 

Kind regards
Finn

**Comment by michevan** [comment]
Thanks Finn! We're working on a fix for this now

**Comment by michevan** [comment]
This is [fixed](https://github.com/google/lightweight_mmm/commit/2881c40c5dd15c09304489bf76c317df5e06acfc) now. Thanks again for flagging this!

**Comment by finn-stein** [comment]
Thanks, I'm happy that this was helpful!
