### ISSUE TITLE
Issues Installing LightWeight MMM on M1 MACOS Montery

### ISSUE THREAD

**Issue by freudianfaults** [google/lightweight_mmm#98]
Tried installing lightweight_mmm using the following commands on python ver 3.9

`pip install lightweight_mmm`

I am currently running to the following error

```
Collecting lightweight_mmm
  Using cached lightweight_mmm-0.1.1-py3-none-any.whl (41 kB)
  Using cached lightweight_mmm-0.1.0-py3-none-any.whl (40 kB)
Requirement already satisfied: jax>=0.2.21 in ./miniforge3/envs/tf_env/lib/python3.9/site-packages (from lightweight_mmm) (0.3.23)
ERROR: Cannot install lightweight-mmm==0.1.0, lightweight-mmm==0.1.1, lightweight-mmm==0.1.2, lightweight-mmm==0.1.3, lightweight-mmm==0.1.4, lightweight-mmm==0.1.5 and lightweight-mmm==0.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    lightweight-mmm 0.1.6 depends on tensorflow>=2.7.2
    lightweight-mmm 0.1.5 depends on tensorflow>=2.7.2
    lightweight-mmm 0.1.4 depends on tensorflow==2.7.2
    lightweight-mmm 0.1.3 depends on tensorflow==2.7.2
    lightweight-mmm 0.1.2 depends on tensorflow==2.5.3
    lightweight-mmm 0.1.1 depends on tensorflow==2.5.3
    lightweight-mmm 0.1.0 depends on tensorflow==2.4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
(tf_env) 
```

Any help would be greatly appreciated

**Comment by pabloduque0** [comment]
Hey @freudianfaults !
I dont have direct experience on M1 Macs but I believe they forked `tensorflow` under `tensorflow-macos`.

You might have to install that first and then proceed installing LMMM.  You can save this as a requirements.txt file and then install it from it (made the switch for your alread):

```
absl-py
arviz==0.11.2
dataclasses;python_version<'3.7'
immutabledict>=2.0.0
jax>=0.3.18
jaxlib>=0.3.18
matplotlib==3.3.4
numpy>=1.12
numpyro>=0.9.2
pandas>=1.1.5
scipy
seaborn==0.11.1
sklearn
tensorflow-macos
typing_extensions;python_version<'3.8'
```

Please feel free to report back as I am unaware of how well this will work.

**Comment by freudianfaults** [comment]
Hi pablo, thanks for your quick response. I already have tensorflow-macos preinstalled before my initial attempt but still ran into the same error above.

I have also attempted using your requirements.txt with the following terminal command

`pip install lightweight_mmm -r requirements.txt`

and also 

`pip install -r requirements .txt` 
followed by
`pip install lightweight_mmm`
but still ran into the same error.

Could this be a compatibility issue with tensorflow-macos ?

**Comment by pabloduque0** [comment]
You might have to add `--no-deps` when Installing `lightweight_mmm` directly since that will try to install `tf` as well.

I not super familiar with `tensorflow-macos` but `tf` is a very side dependency which is only used for a couple things so I think it should be fine.

**Comment by freudianfaults** [comment]
Hi @pabloduque0 the solution you've provided works perfectly ! Thank you so much for your help !
